### ISSUE TITLE
CONTRIBUTING Guide

### ISSUE THREAD

**Issue by JosephMart** [SaltyQuetzals/GoodBullSchedules#44]
Really like code base structure :+1:, the idea, and the fact that the project is open and wouldn't mind contributing. Would be nice if there was a contribution guide/project setup mostly on the part after `npm i` and getting the database up and running locally!

**Comment by SaltyQuetzals** [comment]
You're right! I've gone ahead and taken care of those things. See the bottom of README.md for setup instructions, and CONTRIBUTING.md for contributing guidelines.

**Comment by JosephMart** [comment]
:+1:
